INSERT INTO Estudio VALUES
('Charaction'),
('Sakura Create'),
('Ordet'),
('Jinnis Animation Studios'),
('BOOTLEG'),
('Shin-Ei Animation'),
('Jumondo'),
('Geno Studio'),
('Ishimori Entertainment'),
('Shanghai Foch Film Culture Investment'),
('Graphinica'),
('Mili Pictures'),
('Bandai Namco Pictures'),
('Echoes'),
('Will Palette'),
('Shogakukan Music &amp'),
('G&amp'),
('Idea Factory'),
('G-Lam'),
('TYO Animations'),
('Production I.G'),
('NHK Enterprises'),
('Venet'),
('NUT'),
('Studio Kikan'),
('Encourage Films'),
('Topcraft'),
('Hoods Drifters Studio'),
('Eiken'),
('Kokusai Eigasha'),
('Sotsu'),
('Robot Communications'),
('Tama Production'),
('domerica'),
('Studio VOLN'),
('Nishiki Studio'),
('Amber Film Works'),
('Kinema Citrus'),
('Bridge'),
('MMDGP'),
('Triple X'),
('Pastel'),
('Polygon Pictures'),
('Ekura Animal'),
('PrimeTime'),
('Primastea'),
('pH Studio'),
('Studio Wombat'),
('Japan Vistec'),
('Oddjob'),
('Studio Sign'),
('Kamikaze Douga'),
('Queen Bee'),
('SELFISH'),
('Marvy Jack'),
('Tokyo Kids'),
('Platinum Vision'),
('Studio Core'),
('Bouncy'),
('BreakBottle'),
('Yamamura Animation'),
('Office AO'),
('Phoenix Entertainment'),
('OLM Digital'),
('Opera House'),
('AIC Frontier'),
('D.A.S.T.'),
('Public &amp'),
('Seven Arcs'),
('Studio Ponoc'),
('Chiptune'),
('Circle Tribute'),
('Shinkuukan'),
('A-Real'),
('White Fox'),
('dwarf'),
('Ishikawa Pro'),
('Three-d'),
('Toei Animation'),
('EKACHI EPILKA'),
('Hoods Entertainment'),
('Tomason'),
('Studio G-1Neo'),
('Panda Factory'),
('Piso Studio'),
('Tonko House'),
('Digital Frontier'),
('Daichi Doga'),
('Life Work'),
('Lay-duce'),
('Light Chaser Animation Studios'),
('Karaku'),
('Y.O.U.C'),
('CG Year'),
('Shuka'),
('ILCA'),
('View Works'),
('The Answer Studio'),
('ACC Production'),
('Studio Junio'),
('Kachidoki Studio'),
('Silver Link.'),
('Kaname Productions'),
('Heewon Entertainment'),
('E&amp'),
('Studio Ppuri'),
('Trigger'),
('Studio Binzo'),
('Sprite Animation Studios'),
('Tomovies'),
('Anpro'),
('Studio Hakk'),
('Office Take Off'),
('Onionskin'),
('Hotline'),
('Next Media Animation'),
('T-Rex'),
('Sunwoo Entertainment'),
('10Gauge'),
('Kanaban Graphics'),
('Usagi Ou'),
('October Media'),
('Shimogumi'),
('Studio 9 MAiami'),
('Studio Jam'),
('Bones'),
('Khara'),
('Future Planet'),
('Hiro Media'),
('Science SARU'),
('FOREST Hunting One'),
('Production Reed'),
('Felix Film'),
('Sparkly Key Animation Studio'),
('Mushi Production'),
('Team YokkyuFuman'),
('M2'),
('Steve N&#039'),
('Manglobe'),
('Karasfilms'),
('Triangle Staff'),
('Kyotoma'),
('Plum'),
('Connect'),
('Annapuru'),
('C2C'),
('PoRO'),
('Rikuentai'),
('Rabbit Machine'),
('NAZ'),
('Think Corporation'),
('Kino Production'),
('Namu Animation'),
('Project No.9'),
('Studio WHO'),
('Beijing Huihuang Animation Company'),
('Echo'),
('Tezuka Productions'),
('Daewon Media'),
('Ripromo'),
('Remic'),
('Kenji Studio'),
('Puzzle Animation Studio Limited'),
('Animate Film'),
('Seven Arcs Pictures'),
('Big Bang'),
('AIC Takarazuka'),
('Media Bank'),
('Studio Fantasia'),
('D &amp'),
('Trinet Entertainment'),
('Mary Jane'),
('Pierrot Plus'),
('Studio Gokumi'),
('JCF'),
('Studio Flad'),
('Yokohama Animation Lab'),
('Success Co.'),
('A-Line'),
('DLE'),
('Visual 80'),
('APPP'),
('MooGoo'),
('Shirogumi'),
('Tsuchida Productions'),
('Gainax'),
('David Production'),
('Lerche'),
('Seven'),
('Imagineer'),
('Image House'),
('CoMix Wave Films'),
('Studio Korumi'),
('Animation Do'),
('EDGE'),
('Himajin Planning'),
('Studio Ghibli'),
('Odolttogi'),
('Dongyang Animation'),
('iDRAGONS Creative Studio'),
('AIC Spirits'),
('Office Nobu'),
('Studio Deen'),
('Fuji TV'),
('Yaoyorozu'),
('Daume'),
('EMT²'),
('Oxybot'),
('Buemon'),
('Joker Films'),
('PRA'),
('Gathering'),
('feel.'),
('Cygames'),
('Oh! Production'),
('Tomoyasu Murata Company'),
('Rising Force'),
('Studio Moriken'),
('ChuChu'),
('Shueisha'),
('Dwango'),
('DMM.futureworks'),
('Studio Hibari'),
('Wit Studio'),
('RG Animation Studios'),
('Qualia Animation'),
('Radix'),
('Studio Kyuuma'),
('Studio 1st'),
('Rabbit Gate'),
('AIC Build'),
('TNK'),
('production doA'),
('Schoolzone'),
('Picograph'),
('Pb Animation Co. Ltd.'),
('Purple Cow Studio Japan'),
('Agent 21'),
('Tri-Slash'),
('GARDEN LODGE'),
('SOEISHINSHA'),
('Larx Entertainment'),
('Collaboration Works'),
('Kazuki Production'),
('HS Pictures Studio'),
('AXsiZ'),
('Nippon Animation'),
('Creators Dot Com'),
('Signal. MD'),
('Chippai'),
('Genco'),
('HeART-BIT'),
('Enoki Films'),
('Doga Kobo'),
('Studio A-CAT'),
('Panmedia'),
('BeSTACK'),
('Blue Cat'),
('Milky Animation Label'),
('Studio Lings'),
('Front Line'),
('ixtl'),
('Code'),
('Chaos Project'),
('Studio Egg'),
('Thundray'),
('Bee Media'),
('Boyan Pictures'),
('3xCube'),
('Azeta Pictures'),
('TYPHOON GRAPHICS'),
('Telecom Animation Film'),
('Studio Pierrot'),
('Studio LAN'),
('Asread'),
('SynergySP'),
('Fanworks'),
('Arms'),
('Ascension'),
('Anime R'),
('Madhouse'),
('Telescreen BV'),
('Office Takeout'),
('TROYCA'),
('Studio Chizu'),
('Shanghai Animation Film Studio'),
('Studio Blanc'),
('Minami Machi Bugyousho'),
('Tatsunoko Production'),
('Tamura Shigeru Studio'),
('Piko Studio'),
('AIC Classic'),
('AIC Plus+'),
('KeyEast'),
('Magic Bus'),
('Picture Magic'),
('Emon'),
('M.S.C'),
('Nexus'),
('Aubec'),
('Wawayu Animation'),
('Strawberry Meets Pictures'),
('PPM'),
('Neft Film'),
('Creators in Pack'),
('Egg'),
('Calf Studio'),
('DR Movie'),
('CloverWorks'),
('Nice Boat Animation'),
('Inc.'),
('Beijing Rocen Digital'),
('ufotable'),
('Issen'),
('Studio Unicorn'),
('Toei Video'),
('Flavors Soft'),
('Palm Studio'),
('Digital Media Lab'),
('NHK'),
('Xebec'),
('Marine Entertainment'),
('Hal Film Maker'),
('Meruhensha'),
('Studio Meditation With a Pencil'),
('Sugar Boy'),
('Studio Zealot'),
('Nomad'),
('C-Station'),
('Haoliners Animation League'),
('B&amp'),
('Indeprox'),
('Egg Firm'),
('GANSIS'),
('Moss Design Unit'),
('Blade'),
('LIDENFILMS'),
('Studio Gallop'),
('Asura Film'),
('Shaft'),
('Artland'),
('Dynamo Pictures'),
('Husio Studio'),
('WAO World'),
('Kazami Gakuen Koushiki Douga-bu'),
('G.CMay Animation &amp'),
('Darts'),
('SANZIGEN'),
('KAGAYA Studio'),
('Trans Arts'),
('Fukushima Gainax'),
('Studio Animal'),
('Tengu Kobo'),
('Fifth Avenue'),
('Studio Comet'),
('REALTHING'),
('GEMBA'),
('KIZAWA Studio'),
('Studio Take Off'),
('Sting Ray'),
('Studio Nue'),
('Studio Zero'),
('Asahi Production'),
('OLM'),
('drop'),
('Rockwell Eyes'),
('81 Produce'),
('AIC A.S.T.A.'),
('GoHands'),
('Pie in The Sky'),
('Ripple Film'),
('Ajia-Do'),
('Yamato Works'),
('Lesprit'),
('Takara Tomy A.R.T.S'),
('8bit'),
('Mook DLE'),
('DAX Production'),
('Bee Train'),
('Brain&#039'),
('L²Studio'),
('Planet'),
('Studio Rikka'),
('Orange'),
('Vega Entertainment'),
('Sunrise'),
('Office DCI'),
('Zero-G'),
('Tsukimidou'),
('KOO-KI'),
('Pine Jam'),
('Nakamura Production'),
('Animaruya'),
('Cookie Jar Entertainment'),
('Tokyo Movie Shinsha'),
('J.C.Staff'),
('Passione'),
('Minakata Laboratory'),
('A.C.G.T.'),
('LandQ studios'),
('Square Enix'),
('Studio Live'),
('Studio Anima'),
('Kitty Films'),
('Dongwoo A&amp'),
('Studio World'),
('Studio 3Hz'),
('Oz'),
('LMD'),
('Studio CA'),
('AIC'),
('TAKI Corporation'),
('Vasoon Animation'),
('REVOROOT'),
('Xebec Zwei'),
('Diomedea'),
('Anime Antenna Iinkai'),
('G-angle'),
('Lilix'),
('Suzuki Mirano'),
('Studio Flag'),
('Studio Colorido'),
('Gonzo'),
('Arcs Create'),
('Sanrio'),
('Actas'),
('Studio Khronos'),
('MAPPA'),
('Barnum Studio'),
('An DerCen'),
('Studio 4°C'),
('teamKG'),
('DandeLion Animation Studio LLC'),
('Milky Cartoon'),
('Gakken Eigakyoku'),
('Marza Animation Planet'),
('Studio Eromatick'),
('Zexcs'),
('Knack Productions'),
('Kyoto Animation'),
('Studio PuYUKAI'),
('Japan Taps'),
('Natural High'),
('Craftar'),
('Shochiku Animation Institute'),
('Studio! Cucuri'),
('Amuse'),
('2:10 Animation'),
('Yumeta Company'),
('Pollyanna Graphics'),
('Millepensee'),
('Green Bunny'),
('A-1 Pictures'),
('Studio Bogey'),
('Group TAC'),
('Ginga Ya'),
('Satelight'),
('W-Toon Studio'),
('Artmic'),
('Dai Nippon Printing'),
('Ashi Production'),
('Coastline Animation Studio'),
('TUBA'),
('Production IMS'),
('Majin'),
('Studio Matrix'),
('P.A. Works'),
('helo.inc'),
('Pink Pineapple'),
('AT-2'),
('TMS Entertainment'),
('Tele-Cartoon Japan'),
('Imagin'),
('Pops Inc.'),
('TOCSIS');
